FROM yiisoftware/yii2-php:8.2-fpm-nginx
# FROM yiisoftware/yii2-php:8.1-apache

# Change document root for Apache
# RUN sed -i -e 's|/app/web|/app/backend/web|g' /etc/apache2/sites-available/000-default.conf

# Change document root for nginx
# RUN sed -i -e s|/app/web|/app/backend/web|g'' /etc/nginx/conf.d/default.conf
