name: Go CI

run-name: ${{ github.actor }} is learning GitHub Actions

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
      - name: demo
        run: go version

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
      - name: build
        run: go build -o hello .
      - uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: hello
