on:
  workflow_run:
    workflows: ["Go CI"]
    types:
      - requested
      - in_progress
      - completed

name: IM Notification

jobs:
  notification:
    name: IM Notification
    runs-on: ubuntu-latest
    steps:
    - name: Send feishu message
      env:
        ACTIONS_FEISHU_TAG: 'v1.3.1'
        INPUT_WEBHOOK: "${{ secrets.NOTIFY_WEBHOOK }}"
        INPUT_MESSAGE_TYPE: "post"
        INPUT_TITLE: "${{ github.repository }} in ${{ github.event.action }}"
        INPUT_CONTENT: "I'm message body\nfrom: ${{ github.repository }}"
      run: |
        wget -q https://github.com/xiachufang/actions-feishu/releases/download/${{ env.ACTIONS_FEISHU_TAG }}/linux-amd64-actions-feishu.tar.gz
        tar zxf linux-amd64-actions-feishu.tar.gz feishu
        ./feishu
